name: Auto-approve Renovate

on:
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'

jobs:
  auto-approve:
    uses: luno/.github/.github/workflows/auto-approve-renovate.yml@main
    permissions:
      pull-requests: write
